-- Seed data: roles, permissions, role-permission grants, default admin user, and settings.
-- Requirement doc §2 "suggested roles": Admin, Hasbeh Employee, Accountant, Viewer.
-- Requirement doc §5: default commission rate 7%, stored as a Setting so it can change later.

BEGIN;

INSERT INTO roles (name, description) VALUES
    ('Admin',            'Full access to every screen and action, including user management.'),
    ('HasbehEmployee',   'Day-to-day market operations: create invoices, manage partners, record payments.'),
    ('Accountant',       'Financial views and reports; can record payments/expenses but not manage users.'),
    ('Viewer',           'Read-only access to invoices, partners, and reports.');

INSERT INTO permissions (key, description) VALUES
    ('invoices.create', 'Create a new sales invoice'),
    ('invoices.edit',   'Edit an existing invoice'),
    ('invoices.cancel', 'Cancel/void an invoice'),
    ('invoices.view',   'View invoices'),
    ('partners.manage', 'Create/edit farmers and merchants'),
    ('partners.view',   'View farmers and merchants'),
    ('payments.create', 'Record a payment'),
    ('payments.view',   'View payments'),
    ('expenses.manage', 'Create/edit market expenses'),
    ('reports.view',    'View reports'),
    ('reports.export',  'Export reports to PDF/Excel'),
    ('settings.manage',  'Change system settings (e.g. commission rate)'),
    ('users.manage',     'Create/edit/enable/disable user accounts and roles');

-- Admin: everything.
INSERT INTO role_permissions (role_id, permission_id)
SELECT (SELECT id FROM roles WHERE name = 'Admin'), id FROM permissions;

-- HasbehEmployee: day-to-day operations, no user/settings management.
INSERT INTO role_permissions (role_id, permission_id)
SELECT (SELECT id FROM roles WHERE name = 'HasbehEmployee'), id FROM permissions
WHERE key IN ('invoices.create','invoices.edit','invoices.view',
              'partners.manage','partners.view',
              'payments.create','payments.view',
              'reports.view');

-- Accountant: financial focus.
INSERT INTO role_permissions (role_id, permission_id)
SELECT (SELECT id FROM roles WHERE name = 'Accountant'), id FROM permissions
WHERE key IN ('invoices.view','partners.view',
              'payments.create','payments.view',
              'expenses.manage',
              'reports.view','reports.export');

-- Viewer: read-only.
INSERT INTO role_permissions (role_id, permission_id)
SELECT (SELECT id FROM roles WHERE name = 'Viewer'), id FROM permissions
WHERE key IN ('invoices.view','partners.view','payments.view','reports.view');

-- Default admin login: username "admin", password "ChangeMe123!" — HASH BELOW IS A PLACEHOLDER.
-- The real PBKDF2 hash+salt pair is generated by GreenMarket.Api on first run (see
-- Infrastructure/Persistence/Seed/DbSeeder.cs) — this row exists so the schema is
-- immediately queryable; the API's seeder UPSERTs the real hash over it at startup.
INSERT INTO users (full_name, username, password_hash, password_salt, role_id, is_active)
VALUES ('System Administrator', 'admin', 'PLACEHOLDER_SET_BY_APP_SEEDER', 'PLACEHOLDER',
        (SELECT id FROM roles WHERE name = 'Admin'), TRUE);

INSERT INTO settings (key, value, description) VALUES
    ('commission.default_rate', '0.07', 'Default market commission rate applied to new invoices (requirement doc §5).'),
    ('market.name', 'Green Market', 'Displayed on invoices and reports.'),
    ('whatsapp.business_number', '', 'WhatsApp Business number used to send invoices (requirement doc §9).'),
    ('market.registration_number', '', 'Company/commercial registration number shown on the printed invoice header.'),
    ('market.phone', '', 'Company phone number shown on the printed invoice header.'),
    ('market.address', '', 'Company address shown on the printed invoice header.');

COMMIT;
